spring:
  profiles:
    default: session-memory
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/board_db?connectionTimeZone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:board_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: true
server:
  servlet:
    session:
      cookie:
        name: SESSION
        http-only: true
        same-site: lax
